name: CI

on: [pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-latest
          - windows-latest
          # - ubuntu-latest
        lua:
          # - {hererocks: "-l 5.1", name: "Lua 5.1"}
          # - {hererocks: "-j latest", name: "LuaJIT-latest"}
          # - {hererocks: "-m latest", name: "MoonJIT-latest"}
          # - {hererocks: "-l 5.2", name: "Lua 5.2"}
          # - {hererocks: "-l 5.3", name: "Lua 5.3"}
          - {hererocks: "-l 5.4", name: "Lua 5.4"}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: hererocks
      - name: ${{ matrix.lua.name }} setup
        run: python -m hererocks ${{ matrix.lua.hererocks }} -rlatest .luaenv
      - name: Install
        run: |
          . ./.luaenv/bin/activate
          luarocks make
          luarocks install busted
      - name: Run tests
          . ./.luaenv/bin/activate
          busted tests
