name: CI

on: [pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - {name: macos-latest, setupscript: "export MACOSX_DEPLOYMENT_TARGET='10.8' CFLAGS='-DLUAJIT_ENABLE_GC64'"}
          - {name: windows-latest, setupscript: ""}
          - {name: ubuntu-latest, setupscript: ""}
        lua:
          - {hererocks: "-l 5.1", name: "Lua 5.1"}
          - {hererocks: "-j latest", name: "latest LuaJIT"}
          - {hererocks: "-m latest", name: "latest MoonJIT"}
          - {hererocks: "-l 5.2", name: "Lua 5.2"}
          - {hererocks: "-l 5.3", name: "Lua 5.3"}
          - {hererocks: "-l 5.4", name: "Lua 5.4"}

    runs-on: ${{ matrix.os.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: hererocks

      # - name: Set up ${{ matrix.lua.name }} for MacOS environment
      #   if: ${{ matrix.os == 'macos-latest' }}
      #   run: |
      #     python -m hererocks ${{ matrix.lua.hererocks }} -rlatest .luaenv

      - name: Set up ${{ matrix.lua.name }}
        run: |
          ${{ matrix.os.setupscript }}
          python -m hererocks ${{ matrix.lua.hererocks }} -rlatest .luaenv

      - name: Install vectorize and busted
        run: |
          . ./.luaenv/bin/activate
          luarocks make
          luarocks install busted
      - name: Run tests
        run: |
          . ./.luaenv/bin/activate
          busted tests
