# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-53-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: 5.3

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install Module and Busted
        run: |
          luarocks make
          luarocks install busted

      - name: Run Core Tests
        run: |
          busted tests/core.lua

  test-54-ubuntu:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: 5.4

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install Module and Busted
        run: |
          luarocks make
          luarocks install busted

      - name: Run Core Tests
        run: |
          busted tests/core.lua
