name: CI

on: [pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        lua:
          - "5.1"
          - "luajit-2.0.5"
          - "5.2"
          - "5.3"
          - "5.4"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.lua }}

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install Module and Busted
        run: |
          luarocks make
          luarocks install busted

      - name: Run Core Tests
        run: |
          busted tests
