# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-53:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          # The version of Lua to install, must be available on https://www.lua.org/ftp/ or http://luajit.org/download.html
          luaVersion: 5.3

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      # Runs a single command using the runners shell
      - name: Install Module and Busted
        run: |
          luarocks install vectorize-scm-0.rockspec
          luarocks install busted
      
      - name: Run Core Tests
        run: busted tests/core.lua
