name: CI

on: [pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          # - ubuntu-latest
        lua:
          - {hererocks: "-l 5.1", name: "5.1"}
          - {hererocks: "-j latest", name: "LuaJIT-latest"}
          - {hererocks: "-m latest", name: "MoonJIT-latest"}
          - {hererocks: "-l 5.2", name: "5.2"}
          - {hererocks: "-l 5.3", name: "5.3"}
          - {hererocks: "-l 5.4", name: "5.4"}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            hererocks
      - run: |
          echo "Setting up for ${{ matrix.lua.name }}"
          python -m hererocks ${{ matrix.lua.hererocks }} -rlatest .luaenv
      - run: |
          . ./.luaenv/bin/activate
          luarocks make
          luarocks install busted
          . ./.luaenv/bin/activate
          busted tests
